### ISSUE TITLE
Split tunnel resolution fails

### ISSUE THREAD

**Issue by SteveSyfuhs** [MichaCo/DnsClient.NET#112]
I have a simple bit of code that looks for an SRV record:

```csharp
var client = new LookupClient();
var response = await client.QueryAsync("_thing._thing.domain.com", QueryType.SRV);
```
```
Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19043
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.203\

Host (useful for support):
  Version: 5.0.6
  Commit:  478b2f8c0e
```

This generally works fine and I otherwise haven't had any issues with it. Recently however, I've been trying to run it on a machine that has a VPN that uses split tunneling, where the DNS server I want to resolve is on the other side of the VPN.

Looking at the code I see it gets the list of native interfaces through `NetworkInterface.GetAllNetworkInterfaces()` or the native path:

https://github.com/MichaCo/DnsClient.NET/blob/1ecf8701d70eaaaf24f1fdda8e0cf188e1574334/src/DnsClient/NameServer.cs#L211-L224

In either case both do return the VPN interface, but the interface has no DNS endpoint configured, meaning this library can't resolve the VPN'ed DNS name server.

If I do any DNS queries through the OS APIs requiring this VPN'ed DNS server, everything works. Clearly the OS is aware enough to send the DNS requests over the VPN to...some name server.

Any idea how to inform this library of that other name server?

**Comment by MichaCo** [comment]
Ok, well, that's interesting I guess.

Regarding your question of how to inform the library...
DnsClient relies only on that `NetworkInterface.GetAllNetworkInterfaces` API, if the DNS Servers are not configured on the network interface then it cannot really get that information by itself.
You can of course always pass in DNS Servers manually when creating an instance of the client, though, or use `QueryServer` instead of `Query`.

I'm curious though if there is anything the library could do. I'm not really a Windows networking expert, meaning, if I knew some tricks I'd probably already implemented that ^^

But lets maybe try to get some more information.
From my experience, when I work on my work-laptop for example, the VPN connection has its own "virtual" network adapter which also has at least one DNS server configured which can resolve names in the internal network.
My company uses Windows 10 Always On VPN (AOVPN) and SplitTunneling enabled.

Split Tunnel basically just means that you can connect to both, the internet (using your ISP's DNS at the end) and the internal VPN network via internal DNS servers. But that also means that both Network Interfaces must be configured correctly with DNS Servers...

`NetworkInterface.GetAllNetworkInterfaces()` should return both (or more) interfaces, similar to what you get from `IPCONFIG /ALL`.

Could you check what both methods return in your case? `IPCONFIG /ALL` and the NetworkInterface APIs?

Could you also check if Nrpt policies are enabled. That's a policy based "hardcoded" DNS resolution in Windows.
You'd need an elevated powershell prompt and check if it is enabled via `Get-DnsClientNrptGlobal` or check if there are any policies via `Get-DnsClientNrptPolicy`.

**Comment by SteveSyfuhs** [comment]
Aha, the issue is a set of additional NRPT policies. This is what's allowing DNS to work. I didn't even know this was a thing in Windows. TIL!

As it stands, the following code works. It's unclear to me if this is an appropriate method of querying all this information though. I'm inclined to think it's not, but I will ask the DNS team directly to see if there's a more appropriate public API to get this information.

Would you be willing to accept a PR with such a change to support this?

```csharp
var reg = Registry.LocalMachine.OpenSubKey(@"SYSTEM\CurrentControlSet\Services\Dnscache\Parameters\DnsPolicyConfig\");

var nameServers = new HashSet<string>();

foreach (var key in reg.GetSubKeyNames())
{
    var entry = reg.OpenSubKey(key);
    var dnsServer = entry.GetValue("GenericDNSServers")?.ToString();

    if (!string.IsNullOrWhiteSpace(dnsServer))
    {
        var split = dnsServer.Split(';', StringSplitOptions.RemoveEmptyEntries);

        foreach (var s in split)
        {
            nameServers.Add(s);
        }
    }
}

DnsClient.LookupClient client = new DnsClient.LookupClient(new LookupClientOptions(nameServers.Select(ns => new NameServer(IPAddress.Parse(ns))).ToArray())
{
    UseTcpOnly = true
});

var result = client.Query("_thing._thing.domain.com", QueryType.SRV);
```

**Comment by SteveSyfuhs** [comment]
Not necessarily that specific code of course, something more production-worthy.

**Comment by MichaCo** [comment]
Regarding a PR, sure, why not.

That being said, I'll probably have a hard time testing this at all, so I guess all I'll test is that it'll not break if all that doesn't exists ^^. And it also has to work on non-windows environments, meaning, it should not throw an error or something if there is no registry.



I was just looking a bit more into that policies stuff and found a spec in the MS docs:
https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-gpnrpt/8cc31cb9-20cb-4140-9e85-3e08703b4745
=> https://winprotocoldoc.blob.core.windows.net/productionwindowsarchives/MS-GPNRPT/%5bMS-GPNRPT%5d.pdf

Looks like there are at least 2 fields with DNS servers?
* DirectAccess DNS Servers
* Generic DNS Servers

Both being a `;` delimited list.

Description says that 
> Data: A semicolon-delimited Unicode **string of IP addresses or names** of DNS servers used for name
resolutions by clients in the absence of DirectAccess settings. Each IP address item in the string
MUST be either an IPv4 address in string format or an IPv6 address in string format. Each
name in the string MUST be an extended hostname, as specified in [MS-HNDS](https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-hnds/eff5b201-ad32-485d-bbed-1d07ad069d5c).

That scares me a little bit because there can be entries which are not IP just IP addresses!?

Then, regarding registry keys, looks like they couldn't pick one location for those settings so there are two, and one gets ignored if both are set:
> <11> Section 2.2.2.8: The DirectAccess DNS Servers key specification is
Software\Policies\Microsoft\Windows NT\DNSClient\DnsPolicyConfig\{Name}. Note that in the
presence of both specified keys, **Windows ignores the
System\CurrentControlSet\services\Dnscache\Parameters key**

**Comment by SteveSyfuhs** [comment]
Oh nice. I wasn't having any luck finding a spec. I did reach out to the DNS dev team though, and I guess if/when they respond they'll point me to this doc.

I'll go ahead and start on this tomorrow. Shouldn't be a lot of work.

I'll gate the call to query the policy based on if the OS is Windows and whether the user has opted in to looking it up. I'll default it to true, because I imagine most folks will want it to mimic existing OS behavior?
