### ISSUE TITLE
Azure Functions - PlatformNotSupportedException unless you mannauly set IPEndPoint

### ISSUE THREAD

**Issue by msdickinson** [MichaCo/DnsClient.NET#133]
Hi, so I have been able to run in azure functions about a year ago but now I am trying again and finding failing.

System.InvalidOperationException: 'Error resolving name servers'
PlatformNotSupportedException: Registry is not supported on this platform.

```
   var client = new LookupClient();
    
```

But the code below is functional. So again I assume this is in azure function not letting me grab the systems DNS settings, so I mannauly setting it works. Creating this here in case its useful for anyone but you can close the ticket.

```
   var client = new LookupClient(NameServer.GooglePublicDnsIPv6);
            var result = client.Query("google.com", QueryType.MX)
                                         .Answers.MxRecords().Any()
                                         ? ValidateEmailDomainResult.Vaild : ValidateEmailDomainResult.Invaild;
```

**Comment by MichaCo** [comment]
This should be fixed with 1.6, I did not test it in azure functions though but the PlatformNotSupportedException should be ignored now.

That doesn't mean that the library will find a DNS server in Azure Functions so you still might have to manually configure the client unless you can use public DNS servers
