### ISSUE TITLE
Not working for Android Oreo

### ISSUE THREAD

**Issue by vbisbest** [MichaCo/DnsClient.NET#17]
I am testing on Android API level 27 and getting an error:

01-07 13:31:44.463 W/ctions.app( 4673): type=1400 audit(0.0:27): avc: denied { read } for name="u:object_r:net_dns_prop:s0" dev="tmpfs" ino=6200 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:net_dns_prop:s0 tclass=file permissive=0

01-07 13:31:44.467 E/libc    ( 4673): Access denied finding property "net.dns1"

A similar report is made here for another app.
https://github.com/c-ares/c-ares/issues/111

You can reproduce this using the Android Emulator and API 27.

**Comment by vbisbest** [comment]
And seems the patch page has a lot of details and how to fix it.
https://github.com/c-ares/c-ares/pull/148

**Comment by MichaCo** [comment]
Well, that sounds horrible - I think, from my perspective I will ignore those kind of issues. 

I don't think it should be in scope for this very simple library to fill gaps in all kinds of mobile APIs/Versions. It would be awesome if it would just work, but hey... 

That means, if you want to use it on devices, you'll be better off passing in a list of name servers to this library and care about retrieving them by yourself (or, if Xamarin handles it reliably, use that^^).

If I find some time, I'll take a look into that stuff again

**Comment by vbisbest** [comment]
Unfortunately Xamarin suffers from the same issues.  My whole challenge revolves around the fact that I need to do SRV lookups which Xamarin does not handle at all, that's where your library comes in.  But I understand your position.   Here is the code to pull DNS addresses for android that works on all platforms including 8.0+.   Feel free to use it in you library.

```
        public List<IPEndPoint> GetDnsServers()
        {
            List<IPEndPoint> endPoints = new List<IPEndPoint>();
            ConnectivityManager connectivityManager = (ConnectivityManager)GlobalDroid.mainActivity.GetSystemService(MainActivity.ConnectivityService);
            
            Network activeConnection = connectivityManager.ActiveNetwork;
            var linkProperties = connectivityManager.GetLinkProperties(activeConnection);

            foreach(InetAddress currentAddress in linkProperties.DnsServers)
            {
                IPEndPoint endPoint = new IPEndPoint(IPAddress.Parse(currentAddress.HostAddress), 53);
                endPoints.Add(endPoint);                
            }

            return endPoints;
        }
```

**Comment by MichaCo** [comment]
/closing this for cleanup. I don't see any reasonable way for me to add device support / more native stuff. I'm actually going to drop some of the existing stuff

**Comment by vitalyster** [comment]
The issue makes this library unusable on Xamarin but it still claims Xamarin support. Please reopen and either fix the issue or drop Xamarin support

**Comment by MichaCo** [comment]
What do you mean with "it still claims Xamarin support"? Where do you read anything about that I claim to support Xamarin?

The problem here is that the "normal" .NET Framework features to find your network's DNS servers might not work on devices.
This library mostly supports what .NET supports, which is primarily `NetworkInterface.GetAllNetworkInterfaces()`. 

Did you try to use the example above using [ConnectivityManager](https://docs.microsoft.com/en-us/dotnet/api/android.net.connectivitymanager?view=xamarin-android-sdk-9) or anything else? 

If you found and configured this library with one or more DNS servers and your app can connect to the network, you should also be able to run queries with DnsClient.

**Comment by vitalyster** [comment]
Well, I create empty Xamarin project, type "Install-Package DnsClient", paste "var client = new LookupClient()" and got crash, for both Android and iOS.
Now I tested with different constructor passing IPEndpoint of DNS server and it works.
Maybe no args constructor should be hidden under `#ifdef __MOBILE__` ?

**Comment by MichaCo** [comment]
`__MOBILE__` symbol isn't available in a `Microsoft.NET.Sdk`, comes from `MSBuild.Sdk.Extras`? 
Not an option here!

Using `LookupClient` with an empty constructor will always only try its best to find DNS servers. There is zero guarantee that this will work in all scenarios. 
In this case, you cannot use that on Android, so, just don't...

To implement an android specific version of DNS Server discovery would require you to pass in a `Android.Content.Context`. Otherwise, I don't thing there is a way a library can retrieve network information and a list of Dns servers (without calling `context.GetSystemService(Context.ConnectivityService)`)

I'm not doing any mobile development, therefore my knowledge about android specific stuff is very limited. The context stuff above is what I found after 10minutes of research. 
So, if you have a better/working alternative for a library to get DNS servers on an Android device, let me know.

Until then /still closed - nothing to do here.

**Comment by vitalyster** [comment]
If I remember correctly - actual problem is broken System.DNS library which tries to do DNS server discovery in the deprecated way which is restricted on current versions of both Android and iOS. 

>  just don't...

Just document it? Or forbid no-args constructor with correct macro :) Android-specific solution is not an option too, do not forget for iOS too :)
