### ISSUE TITLE
Would you consider breaking out core functionality into a separate package?

### ISSUE THREAD

**Issue by matthew-a-thomas** [MichaCo/DnsClient.NET#27]
Or alternatively, would you consider making classes public instead of internal like `DnsDatagramReader`?

Riding on the coattails of #26, it would be really handy to have DNS packet serializing/deserializing broken out as its own thing. Then I would be free to use DNS packets over a totally different medium than unicast DNS (specifically I need mDNS).

I would rather use `DnsClient.NET` as the base for what I need than other packages because of how much more popular `DnsClient.NET` is than the other guys. More popularity = more bugs have been found and fixed = more stable.

I'd be happy to mock up what I mean via a PR. Just let me know.

**Comment by MichaCo** [comment]
Hi @matthew-a-thomas. 
Great idea in general to allow others to use those more low level protocol things.
I made them internal primarily to prevent me from having to care about it when I make changes.
And, I'd have to think more about it / refactor it so that things make sense.

But yeah, my initial idea was to have the whole network and protocol stack abstracted and extensible. Never had the time or need to do that though ;)

Feel free to play with it though, maybe we can get that done together ;)

**Comment by matthew-a-thomas** [comment]
@MichaCo I would like to help here and there as I'm able--thanks for asking. I'll try to have a PR soon that changes the visibility of a few things.

I took a closer look at the source code last night. It looks like we'll need to talk for anything more complex than changing visibility because I think we approach certain things differently. So I would want to make sure we're aligned before I dive in too deep. What's a good channel for chatting with you? Is there a [Gitter community](https://gitter.im) for this repo?

**Comment by matthew-a-thomas** [comment]
@MichaCo Let me know if you did not receive my email. Thanks
