### ISSUE TITLE
Getting "Server Failure" and "Error: No Connection could be established to any.."

### ISSUE THREAD

**Issue by WattsC-90** [MichaCo/DnsClient.NET#46]
I have tried to use the library on my machine, no custom dns servers. literally a copy paste of the code on the readme/wiki/documentation page.

I get errors like: `ServerFailure` and `Error: No Connection could be established to any..<dns servers>`. However `DNS.GetHostEntry` for the same IP will resolve correctly? What causes this exception? Why is this lib getting errors but not the main .net/windows version? Theyre using the same DNS servers!

**Comment by MichaCo** [comment]
DnsClient doesn't use the windows internal APIs and instead connects via UDP (or TCP) port 53 to your DNS server unless configured otherwise.
Seems that connection cannot be established. 

ServerFailure usually is the response from your DNS server which means something on the server is going wrong or you didn't use it right.

Try to use dig or similar tools to connect directly to the same DNS server, you'll most likely get the exact same errors.
