### ISSUE TITLE
Transient issues querying DNS on Azure App Service

### ISSUE THREAD

**Issue by bursteg** [MichaCo/DnsClient.NET#77]
Hi,

I am getting inconsistent experience between running a web app locally and running it on Azure. Used a very basic code to query DNS for the following domains (I am querying for MX records):

1. xelleration.com
Locally: `QueryAsync` returns quickly with no answers
on Azure: times out with the following error: Query 65460 => xelleration.com IN MX on 168.63.129.16:53 timed out or is a transient error. --> The operation was canceled.

2. testtestpbipremium.ccsctp.net
Locally: Getting a valid response
on Azure:  The operation was canceled.

Any idea? Any guidance on using DnsClient on Azure App Service?

Thanks!
Guy

**Comment by MichaCo** [comment]
You are most likely using very different DNS servers locally vs in your web app if you haven't explicitly configured a DNS server IP?

If deployed to app services, it might use the internal Azure DNS which might not be able to resolve certain queries.

If you don't need anything specific, I'd highly recommend to use public DNS servers (like google DNS or any other).

I also ran into some issues myself with https://dnsclient.michaco.net/ and had to disable UDP.
I didn't have time to figure out what was actually going on, so if you find anything, let me know ^^

To disable UDP communication, you can set the LookupClientOptions' TcpOnly to true, and see what happens.

**Comment by sebastiandeuteris** [comment]
Hi @MichaCo for your response. 

We tried to configure TCP, but unfortunately, we received a Forbidden Exception when querying against Azure DNS (not for Google). We could only query through UDP.

We did some tests in Azure comparing Google and Azure DNS and found big differences related to latency. 

Testing the failed domain, mentioned above (_testtestpbipremium.ccsctp.net_), it took less than 1 sec for Google DNS vs 53 seconds for Azure DNS. That's why we are having a timeout exception.

So, apparently It is related to DNS Servers. 
Is it possible that we were missing some configuration related to the interaction within the client and the DNS Server other than using public ones? 

Thanks in advance.

**Comment by MichaCo** [comment]
Mh 1 minute to get a response from Azure DNS sounds fishy. Unfortunately I don't have any experience with those Azure DNS server/services, no idea what you could change.
For the client there is not much todo, it either gets a response in time from the server or it doesn't. There is really nothing special.

You could try to disable EDNS in DnsClient (ExtendedDnsBufferSize is enabled by default, but usually, servers which don't support it simply return 512 bytes and that's it. So I highly doubt that this has any effect on the server response time)

You can ofc also increase the response timeout if you want.

**Comment by sebastiandeuteris** [comment]
Thanks again for your response.

I agree with you, there's no much to do here as there is an issue related to the Server taking much time in resolving domains.
We tried managing timeouts, but I think we'll move forward with public servers as a fallback by adding them to the server's list alongside with Azure DNS. 

Regarding EDNS, it is something we can try anyway and see what happens. 

Thanks for your time!
Seba
