### ISSUE TITLE
Azure Function DI - Failing to resolve 

### ISSUE THREAD

**Issue by msdickinson** [MichaCo/DnsClient.NET#90]
Hi, I am able to DI this just fine in ASP.net, But when i try to DI this in Azure Function Latest (3.0.9) also attempted in (3.0.3) It fails at run time with " Anonymously Hosted DynamicMethods Assembly: Object reference not set to an instance of an object." 

I am able DI without issue for many other things but oddly not for this package.

I can create instance of it just fine instead of a method without DI. but only seems to happen with this package. Clearly this is somthing with the run time env not with DnsClient It self, but I wanted to see if anyone else has ran into this issue.

If it helps I am using "public class Startup : FunctionsStartup"
....
services.TryAddSingleton<ILookupClient, LookupClient>();

**Comment by msdickinson** [comment]
I can only assume some sorta timing issue with azure functions DI. If i do it like this, it works. 
I know it uses a differnt DI provider then asp.net. 

            services.TryAddTransient<ILookupClient>((serviceProvider) =>
            {
                return new LookupClient();
            });

So feel free to close this but still fairly odd to me.

**Comment by MichaCo** [comment]
I guess the DI doesn't use the empty constructor and tries to resolve a LookupClient instance with one of the other constructors which doesn't work because none of the parameters are injected to the DI container to satisfy the ctor dependencies. And then the DI just returns null?
But yeah, your fix is the right approach in this case.
