### ISSUE TITLE
Contradiction in documentation for ContinueOnDnsError and ThrowDnsErrors

### ISSUE THREAD

**Issue by L3gume** [MichaCo/DnsClient.NET#93]
There seems to be a contradiction in the documentation here: https://dnsclient.michaco.net/docs/DnsClient.DnsQueryOptions.html#DnsClient_DnsQueryOptions_ContinueOnDnsError

#### In the section for `ContinueOnDnsError`:

Remarks
If True, lookup client will continue until a server returns a valid result, or, if no NameServers yield a valid result, the last response with the error will be returned. In case no server yields a valid result and ThrowDnsErrors is also enabled, an exception will be thrown containing the error of the last response.

If True and ThrowDnsErrors is enabled, the exception will be thrown on first encounter without trying any other servers.

#### In the section for `ThrowDnsErrors`:

If both, ContinueOnDnsError and ThrowDnsErrors are set to True, ILookupClient will continue to query all configured NameServers. If none of the servers yield a valid response, a DnsResponseException will be thrown with the error of the last response.

What is the actual behavior when both of them are set to `true`? From my very quick tests it seems it behaves like what is described in the `ContinueOnDnsError` section.

**Comment by MichaCo** [comment]
It should behave as documented, if both are true, all servers should be called and if all fail the last error will be thrown.
If that's not how the client behaves I might have introduced that bug with the last error rework update. Can you confirm (show logs) that it throws an error after the first (out of many) server returned an error?

**Comment by L3gume** [comment]
Thanks for the quick response!  

Please correct me if I'm wrong here, I am having a bit of trouble understanding the behavior but I think I may know what is happening.

I have 3 name servers to query, `ContinueOnDnsError` and `ContinueOnEmptyResponse` are `true` and `ThrowOnDnsError` is `false`. In my use case, I consider an empty response as valid since I am querying for CAA records.

Here's what I think is happening:  
* the first name server returns a `FORMERR` status, `ContinueOnDnsError` is `true` so we move on.
* the second and third name servers both return an empty response since the queried domain has no CAA records.
* an exception is then thrown for the `FORMERR` status since it is the last error and empty results aren't considered as valid.

**Comment by L3gume** [comment]
Update: setting `ContinueOnEmptyResponse` to `false` seems to have solve the issue. However, this isn't really an acceptable fix as I may still miss out on some results from the next name server.

Is there currently a setting to consider empty responses as valid when `ContinueOnDnsError` is `true` so that no error is thrown when one of the name servers returned an error?

**Comment by L3gume** [comment]
Also is the LookupClient supposed to throw `DnsResponseException` when `ThrowDnsErrors` is set to `false`? right it most definitely does.

**Comment by MichaCo** [comment]
> Also is the LookupClient supposed to throw DnsResponseException when ThrowDnsErrors is set to false? Right now it most definitely does.

See #99. DnsResponseException is just the exception type which will be thrown on timeouts etc. ThrowDnsError only affects protocol related errors, like the DNS server returns an error code.
This works as expected.

---

Regarding `ContinueOnEmptyResponse` and `ContinueOnDnsError`.
The behavior you describe with settings both true or `ContinueOnEmptyResponse` to false is exactly the expected outcome and should hopefully be clear enough in the API documentation.

(Again, DNS Errors are only protocol related errors, like the Server returns that it doesn't know that domain.)

`ContinueOnEmptyResponse` instructs the LookupClient to try the next DNS server if the current server didn't return any records. 
So, if you consider an empty response as valid, you have to set that flag to false. 
And yes, this means the client might get an empty response from the first of your 3 configured servers and return it. That's the expected behavior because.

> Is there currently a setting to consider empty responses as valid when ContinueOnDnsError is true so that no error is thrown when one of the name servers returned an error?

That's not how this library currently behaves. If e..g. the first call had a DNS error and the second returns an empty result, you WILL get the empty result and no error.

Just added a unit test to my PR here #89 to validate that behavior, and it seems to work just fine.
